# docker-compose.override.yml für bike-doctor-erp
# Erstellt am: 2025-05-05
# Letzte Änderung: Anpassung für die Integration der bikedoctor-App
# Diese Datei erweitert die Standard-Docker-Compose-Konfiguration um projektspezifische Anpassungen

services:
  configurator:
    environment:
      - INSTALL_APPS=erpnext
    volumes:
      - ./custom_apps:/home/frappe/frappe-bench/apps/bikedoctor

  backend:
    volumes:
      - ./custom_apps:/home/frappe/frappe-bench/apps/bikedoctor

  frontend:
    ports:
      - "80:8080"
      - "443:443"

  queue-short:
    volumes:
      - ./custom_apps:/home/frappe/frappe-bench/apps/bikedoctor

  queue-long:
    volumes:
      - ./custom_apps:/home/frappe/frappe-bench/apps/bikedoctor

  queue-default:
    volumes:
      - ./custom_apps:/home/frappe/frappe-bench/apps/bikedoctor

  scheduler:
    volumes:
      - ./custom_apps:/home/frappe/frappe-bench/apps/bikedoctor

  websocket:
    volumes:
      - ./custom_apps:/home/frappe/frappe-bench/apps/bikedoctor