# docker-compose.simple.yml für bike-doctor-erp
# Erstellt am: 2025-05-05
# Letzte Änderung: Vereinfachte Konfiguration mit dem offiziellen ERPNext-Image
# Dieses Setup verwendet einen einfachen Stack mit ERPNext und separaten Datenbank-/Redis-Containern

version: '3'

services:
  erpnext:
    image: frappe/erpnext-worker:version-15
    container_name: bd-erpnext
    restart: always
    command: >
      bash -c "cd /home/frappe/frappe-bench &&
               bench new-site --mariadb-root-password frappe --admin-password admin bikedoctor.localhost &&
               bench --site bikedoctor.localhost install-app erpnext &&
               bench --site bikedoctor.localhost set-config developer_mode 1 &&
               ln -sf /home/frappe/bikedoctor /home/frappe/frappe-bench/apps/bikedoctor &&
               cd /home/frappe/frappe-bench/apps && 
               echo 'bikedoctor' >> /home/frappe/frappe-bench/sites/apps.txt &&
               bench --site bikedoctor.localhost enable-scheduler &&
               bench start"
    ports:
      - "8000:8000"
      - "9000:9000" 
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites
      - ./bikedoctor:/home/frappe/bikedoctor
    environment:
      - ADMIN_PASSWORD=admin
      - DB_HOST=mariadb
      - DB_PORT=3306
      - REDIS_CACHE=redis://redis-cache:6379/0
      - REDIS_QUEUE=redis://redis-queue:6379/0
      - REDIS_SOCKETIO=redis://redis-socketio:6379/0
      - DEVELOPER_MODE=1
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  mariadb:
    image: mariadb:10.6
    container_name: bd-mariadb
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=frappe
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    container_name: bd-redis-cache
    restart: always
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:alpine
    container_name: bd-redis-queue
    restart: always
    volumes:
      - redis-queue-data:/data

  redis-socketio:
    image: redis:alpine
    container_name: bd-redis-socketio
    restart: always
    volumes:
      - redis-socketio-data:/data

volumes:
  erpnext-sites:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data: