# Docker-Compose-Konfiguration für bike.doctor ERPNext-System
# Basierend auf offizieller frappe_docker Easy Install-Implementierung
# Zuletzt aktualisiert: 2025-05-05
# Erstellt für die Behebung von Redis-Verbindungsproblemen
# Änderungen:
# - Getrennte Redis-Dienste für Cache, Queue und SocketIO
# - Korrekte Image-Tags für ERPNext v15
# - BENCH_LOCAL_REDIS=0 explizit gesetzt
# - Spezifische Umgebungsvariablen für Redis-Hosts

version: '3'

services:
  redis-cache:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-queue-data:/data

  redis-socketio:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-socketio-data:/data

  mariadb:
    image: mariadb:10.6
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=frappe
    volumes:
      - mariadb-data:/var/lib/mysql

  frappe:
    image: frappe/frappe:v15.0.0
    restart: on-failure
    environment:
      - REDIS_CACHE_HOST=redis-cache
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_SOCKETIO_HOST=redis-socketio
      - MARIADB_HOST=mariadb
      - DB_ROOT_USER=root
      - DB_ROOT_PASSWORD=frappe
      - SITE_NAME=bikedoctor.localhost
      - ADMIN_PASSWORD=admin
      - INSTALL_APPS=erpnext
      - BENCH_LOCAL_REDIS=0
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - ./custom_apps:/home/frappe/frappe-bench/custom_apps
    depends_on:
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb

  erpnext:
    image: frappe/erpnext:v15.0.0
    restart: on-failure
    environment:
      - REDIS_CACHE_HOST=redis-cache
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_SOCKETIO_HOST=redis-socketio
      - MARIADB_HOST=mariadb
      - DB_ROOT_USER=root
      - DB_ROOT_PASSWORD=frappe
      - PYTHONPATH=/home/frappe/frappe-bench/apps
      - BENCH_LOCAL_REDIS=0
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/frappe-bench/logs
      - ./custom_apps:/home/frappe/frappe-bench/custom_apps
    depends_on:
      - frappe
      - redis-cache
      - redis-queue
      - redis-socketio
      - mariadb

  websocket:
    image: frappe/frappe:v15.0.0
    restart: on-failure
    command: node /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      - REDIS_CACHE_HOST=redis-cache
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_SOCKETIO_HOST=redis-socketio
      - BENCH_LOCAL_REDIS=0
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
    depends_on:
      - redis-socketio
      - frappe

  web:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - frappe-sites:/usr/share/nginx/html/sites
      - frappe-assets:/usr/share/nginx/html/assets
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frappe
      - erpnext
      - websocket

  worker-default:
    image: frappe/erpnext:v15.0.0
    restart: on-failure
    command: bench worker --queue default
    environment:
      - REDIS_CACHE_HOST=redis-cache
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_SOCKETIO_HOST=redis-socketio
      - BENCH_LOCAL_REDIS=0
      - PYTHONPATH=/home/frappe/frappe-bench/apps
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis-queue
      - erpnext

  worker-short:
    image: frappe/erpnext:v15.0.0
    restart: on-failure
    command: bench worker --queue short
    environment:
      - REDIS_CACHE_HOST=redis-cache
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_SOCKETIO_HOST=redis-socketio
      - BENCH_LOCAL_REDIS=0
      - PYTHONPATH=/home/frappe/frappe-bench/apps
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis-queue
      - erpnext

  worker-long:
    image: frappe/erpnext:v15.0.0
    restart: on-failure
    command: bench worker --queue long
    environment:
      - REDIS_CACHE_HOST=redis-cache
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_SOCKETIO_HOST=redis-socketio
      - BENCH_LOCAL_REDIS=0
      - PYTHONPATH=/home/frappe/frappe-bench/apps
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis-queue
      - erpnext

  scheduler:
    image: frappe/erpnext:v15.0.0
    restart: on-failure
    command: bench schedule
    environment:
      - REDIS_CACHE_HOST=redis-cache
      - REDIS_QUEUE_HOST=redis-queue
      - REDIS_SOCKETIO_HOST=redis-socketio
      - BENCH_LOCAL_REDIS=0
      - PYTHONPATH=/home/frappe/frappe-bench/apps
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - frappe-logs:/home/frappe/frappe-bench/logs
    depends_on:
      - redis-queue
      - erpnext

volumes:
  frappe-sites:
  frappe-logs:
  frappe-assets:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data: