# Docker-Compose-Konfiguration für bike.doctor ERPNext-System
# Basierend auf offizieller frappe_docker-Implementierung
# Zuletzt aktualisiert: 2025-05-05
# Änderungen: 
# - Angepasst für bike.doctor mit Site-Name bikedoctor.localhost
# - Verwendung von ERPNext v15 (neueste Version)
# - Einheitliche Datenbankbenutzer und Passwörter
# - Redis-Konfiguration korrigiert für Docker-Networking mit REDIS_CACHE_URL
# - Port-Exposition des Frontend-Containers für direkten Zugriff
# - Hinzufügung der fehlenden MariaDB- und Redis-Dienste
# - Custom-Apps-Verzeichnis als Volume eingebunden für bikedoctor-App

x-customizable-image: &customizable_image
  # By default the image used only contains the `frappe` and `erpnext` apps.
  # See https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md
  # about using custom images.
  image: ${CUSTOM_IMAGE:-frappe/erpnext}:${CUSTOM_TAG:-$ERPNEXT_VERSION}
  pull_policy: ${PULL_POLICY:-always}
  restart: ${RESTART_POLICY:-unless-stopped}

x-depends-on-configurator: &depends_on_configurator
  depends_on:
    configurator:
      condition: service_completed_successfully

x-backend-defaults: &backend_defaults
  <<: [*depends_on_configurator, *customizable_image]
  volumes:
    - sites:/home/frappe/frappe-bench/sites
    - ./custom_apps:/home/frappe/frappe-bench/custom_apps

services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-frappe}
      - MYSQL_USER=${DB_ROOT_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-frappe}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: on-failure

  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-data:/data

  configurator:
    <<: *customizable_image
    platform: linux/amd64
    command:
      - configure.py
    environment:
      DB_HOST: mariadb
      DB_PORT: "3306"
      REDIS_CACHE: redis:6379
      REDIS_QUEUE: redis:6379
      REDIS_SOCKETIO: redis:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ./custom_apps:/home/frappe/frappe-bench/custom_apps

  backend:
    <<: *backend_defaults
    platform: linux/amd64
    environment:
      - REDIS_CACHE_URL=redis://redis:6379/0
      - REDIS_QUEUE_URL=redis://redis:6379/1
      - REDIS_SOCKETIO_URL=redis://redis:6379/2

  frontend:
    <<: *customizable_image
    platform: linux/amd64
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      SOCKETIO: websocket:9000
      FRAPPE_SITE_NAME_HEADER: ${FRAPPE_SITE_NAME_HEADER:-$$host}
      UPSTREAM_REAL_IP_ADDRESS: ${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      UPSTREAM_REAL_IP_HEADER: ${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      UPSTREAM_REAL_IP_RECURSIVE: ${UPSTREAM_REAL_IP_RECURSIVE:-off}
      PROXY_READ_TIMEOUT: ${PROXY_READ_TIMEOUT:-120}
      CLIENT_MAX_BODY_SIZE: ${CLIENT_MAX_BODY_SIZE:-50m}
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ./custom_apps:/home/frappe/frappe-bench/custom_apps

  queue-short:
    <<: *backend_defaults
    platform: linux/amd64
    command: bench worker --queue short
    environment:
      - REDIS_CACHE_URL=redis://redis:6379/0
      - REDIS_QUEUE_URL=redis://redis:6379/1
      - REDIS_SOCKETIO_URL=redis://redis:6379/2

  queue-long:
    <<: *backend_defaults
    platform: linux/amd64
    command: bench worker --queue long,default,short
    environment:
      - REDIS_CACHE_URL=redis://redis:6379/0
      - REDIS_QUEUE_URL=redis://redis:6379/1
      - REDIS_SOCKETIO_URL=redis://redis:6379/2

  scheduler:
    <<: *backend_defaults
    platform: linux/amd64
    command: bench schedule
    environment:
      - REDIS_CACHE_URL=redis://redis:6379/0
      - REDIS_QUEUE_URL=redis://redis:6379/1
      - REDIS_SOCKETIO_URL=redis://redis:6379/2

  websocket:
    <<: *backend_defaults
    platform: linux/amd64
    command: node /home/frappe/frappe-bench/apps/frappe/socketio.js
    environment:
      - REDIS_CACHE_URL=redis://redis:6379/0
      - REDIS_QUEUE_URL=redis://redis:6379/1
      - REDIS_SOCKETIO_URL=redis://redis:6379/2

# ERPNext requires local assets access (Frappe does not)
volumes:
  sites:
  mariadb-data:
  redis-data: