# Docker-Compose-Konfiguration für bike.doctor ERPNext-System
# Basierend auf offizieller frappe_docker-Implementierung
# Zuletzt aktualisiert: 2025-05-05
# Änderungen: 
# - Angepasst für bike.doctor mit Site-Name bikedoctor.localhost
# - Verwendung von ERPNext v15 (neueste Version)
# - Einheitliche Datenbankbenutzer und Passwörter
# - Korrektur der Redis-Verbindungen für Docker-Networking
# - Custom-Apps-Verzeichnis als Volume eingebunden für bikedoctor-App
# - Umfassende Konfiguration für Redis mit korrekt formatierten URLs
# - Angepasste Befehle für redis_cache, redis_queue und redis_socketio

version: '3'

services:
  redis:
    image: redis:alpine
    restart: on-failure
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 10
      interval: 5s

  mariadb:
    image: mariadb:10.6
    restart: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
      - --innodb-buffer-pool-size=${MARIADB_INNODB_BUFFER_POOL_SIZE:-512M}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-frappe}
      - MYSQL_USER=${DB_ROOT_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-frappe}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${DB_PASSWORD:-frappe}"]
      timeout: 10s
      retries: 10
      start_period: 30s
      interval: 10s

  erpnext-python:
    image: frappe/erpnext-worker:v15
    restart: on-failure
    environment:
      - FRAPPE_PY=0.0.0.0:8000
      - FRAPPE_WS=0.0.0.0:9000
      - WORKER_CLASS=gthread
      - WORKER_CONNECTIONS=1024
      - TIMEOUT=120
      - REDIS_CACHE=redis://redis:6379/0
      - REDIS_QUEUE=redis://redis:6379/1
      - REDIS_SOCKETIO=redis://redis:6379/2
      - AUTO_MIGRATE=1
      - MARIADB_HOST=mariadb
      - PYTHONPATH=/home/frappe/frappe-bench/apps
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ./custom_apps:/home/frappe/frappe-bench/custom_apps
    depends_on:
      - redis
      - mariadb

  erpnext-socketio:
    image: frappe/frappe-socketio:v15
    restart: on-failure
    depends_on:
      - redis
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    environment:
      - REDIS_CACHE=redis://redis:6379/0
      - REDIS_QUEUE=redis://redis:6379/1
      - REDIS_SOCKETIO=redis://redis:6379/2

  erpnext-worker-default:
    image: frappe/erpnext-worker:v15
    restart: on-failure
    depends_on:
      - redis
      - mariadb
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ./custom_apps:/home/frappe/frappe-bench/custom_apps
    environment:
      - WORKER_TYPE=default
      - REDIS_CACHE=redis://redis:6379/0
      - REDIS_QUEUE=redis://redis:6379/1
      - REDIS_SOCKETIO=redis://redis:6379/2
      - MARIADB_HOST=mariadb
      - PYTHONPATH=/home/frappe/frappe-bench/apps

  erpnext-worker-short:
    image: frappe/erpnext-worker:v15
    restart: on-failure
    depends_on:
      - redis
      - mariadb
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ./custom_apps:/home/frappe/frappe-bench/custom_apps
    environment:
      - WORKER_TYPE=short
      - REDIS_CACHE=redis://redis:6379/0
      - REDIS_QUEUE=redis://redis:6379/1
      - REDIS_SOCKETIO=redis://redis:6379/2
      - MARIADB_HOST=mariadb
      - PYTHONPATH=/home/frappe/frappe-bench/apps

  erpnext-worker-long:
    image: frappe/erpnext-worker:v15
    restart: on-failure
    depends_on:
      - redis
      - mariadb
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ./custom_apps:/home/frappe/frappe-bench/custom_apps
    environment:
      - WORKER_TYPE=long
      - REDIS_CACHE=redis://redis:6379/0
      - REDIS_QUEUE=redis://redis:6379/1
      - REDIS_SOCKETIO=redis://redis:6379/2
      - MARIADB_HOST=mariadb
      - PYTHONPATH=/home/frappe/frappe-bench/apps

  erpnext-scheduler:
    image: frappe/erpnext-worker:v15
    restart: on-failure
    depends_on:
      - redis
      - mariadb
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - ./custom_apps:/home/frappe/frappe-bench/custom_apps
    environment:
      - WORKER_TYPE=scheduler
      - REDIS_CACHE=redis://redis:6379/0
      - REDIS_QUEUE=redis://redis:6379/1
      - REDIS_SOCKETIO=redis://redis:6379/2
      - MARIADB_HOST=mariadb
      - PYTHONPATH=/home/frappe/frappe-bench/apps

  erpnext-nginx:
    image: frappe/erpnext-nginx:v15
    restart: on-failure
    depends_on:
      - erpnext-python
      - erpnext-socketio
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - sites:/usr/share/nginx/html/sites
      - ./custom_apps:/home/frappe/frappe-bench/custom_apps

volumes:
  sites:
  mariadb-data:
  redis-data: