# docker-compose.simple.yml für bike-doctor-erp
# Erstellt am: 2025-05-05
# Vereinfachte Konfiguration mit einem einzelnen Container
# Diese Datei verwendet einen All-in-One ERPNext-Container für einfachere Entwicklung und Tests

version: '3'

services:
  erpnext:
    image: frappe/erpnext:version-15
    container_name: erpnext
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - erpnext-sites:/home/frappe/frappe-bench/sites
      - ./bikedoctor:/home/frappe/frappe-bench/apps/bikedoctor
    environment:
      - ADMIN_PASSWORD=admin
      - DB_HOST=mariadb
      - DB_PORT=3306
      - REDIS_CACHE=redis://redis-cache:6379/0
      - REDIS_QUEUE=redis://redis-queue:6379/0
      - REDIS_SOCKETIO=redis://redis-socketio:6379/0
      - SITE_NAME=bikedoctor.localhost
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio

  mariadb:
    image: mariadb:10.6
    container_name: erpnext-mariadb
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    environment:
      - MYSQL_ROOT_PASSWORD=frappe
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    container_name: erpnext-redis-cache
    restart: always
    volumes:
      - redis-cache-data:/data

  redis-queue:
    image: redis:alpine
    container_name: erpnext-redis-queue
    restart: always
    volumes:
      - redis-queue-data:/data

  redis-socketio:
    image: redis:alpine
    container_name: erpnext-redis-socketio
    restart: always
    volumes:
      - redis-socketio-data:/data

volumes:
  erpnext-sites:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
